### ISSUE TITLE
Wrong evolution when using Newton Propagator?

### ISSUE THREAD

**Issue by alastair-marshall** [QuantumControl-jl/QuantumPropagators.jl#6]
Maybe I'm using the `propagate` function wrongly but here's a not very minimal working example:

```julia
using QuantumPropagators
using LinearAlgebra
ρ0 = [1 0;0 0] .+ 0.0im
ρ0vec = reshape(ρ0, (4))
const sx = [0 1;1 0] .+ 0.0im
super_sx = kron(eye2, sx) - kron(sx', eye2)

T = 1.0
dt = 0.1
N = floor(Int, T/dt)
K = 1 # number of controls
drive = rand(K, N) .* 0.0 .+ 1 * pi

function get_genfunc(drive, sx)
    gen_func = (tlist, i; kwargs...) -> drive[i] * sx 
end

gen_func = get_genfunc(drive, super_sx)
# should be at the half points but for now just at one end
tlist = collect(0:dt:T-dt)
wrk = initpropwrk(ρ0vec, tlist, nothing; method=:newton)

test = propagate(ρ0vec, gen_func, tlist; wrk = wrk)
test ≈ ρ0vec # false

# working version using ExponentialUtilities
using ExponentialUtilities

function test_prop(state, gen_func, tlist)
    ev = copy(state)

    for i = 1:length(tlist)
        H = gen_func(tlist, i)
        ev .= expv(-1.0im * dt, H, ev)
    end
    ev
end

test2 = test_prop(ρ0vec, gen_func, tlist)
test2 ≈ ρ0vec # true
```

**Comment by goerz** [comment]
Maybe I misunderstand the code, but isn’t `test` the propagated state from the original `ρ0vec` for Newton? The `propagate` routine is not in-place

**Comment by goerz** [comment]
Apart from that I *think* `propagate` might be doing one less time step than `test_prop`. It make one step per interval, not one step per time grid point

**Comment by alastair-marshall** [comment]
Yes it is but the evolution should just be a Rabi period so they should end up the same! It's definitely not a good example

**Comment by alastair-marshall** [comment]
Ah okay I can quickly check that

**Comment by alastair-marshall** [comment]
> Apart from that I _think_ `propagate` might be doing one less time step than `test_prop`. It make one step per interval, not one step per time grid point

Yup thats it

**Comment by goerz** [comment]
Ah, it’s not a random pulse, but a pi pulse? But a pi pulse should give you a factor -1. You’d have to do two pi pulses to get back to the original state
